### ISSUE TITLE
Put licence in code repository

### ISSUE THREAD

**Issue by eirnym** [renpy/cardgame#2]
I saw you've provided licence in documentation. Please put it repo as well

**Comment by renpytom** [comment]
Look at index.rst

**Comment by eirnym** [comment]
It's not the same as licence put in the file. I'm not a specialist to guess what the licence it is by text and what I can and I can't. 

GitHub parses licence file and set field on top of the repository. 

Could you please put the licence file into repository to avoid misunderstanding?
